export default {
  en: {
    ISO: "en",
    name: "English",
    localName: "English",
    countries: ["US", "GB", "CA", "AU", "IE", "NZ", "ZA"],
    speakers: 1132000000,
    direction: "LTR",
    script: "Latin",
    difficulty: 10,
    vocabulary: 1000000,
  },
  es: {
    ISO: "es",
    name: "Spanish",
    localName: "Español",
    countries: ["ES", "MX", "AR", "CO", "PE", "VE", "CL", "EC", "GT", "CU"],
    speakers: 559000000,
    direction: "LTR",
    script: "Latin",
    difficulty: 8,
    vocabulary: 150000,
  },
  nl: {
    ISO: "nl",
    name: "Dutch",
    localName: "Nederlands",
    countries: ["NL", "BE", "SR"],
    speakers: 23000000,
    direction: "LTR",
    script: "Latin",
    difficulty: 5,
    vocabulary: 200000,
  },
  de: {
    ISO: "de",
    name: "German",
    localName: "Deutsch",
    countries: ["DE", "AT", "CH"],
    speakers: 92000000,
    direction: "LTR",
    script: "Latin",
    difficulty: 6,
    vocabulary: 330000,
  },
  fr: {
    ISO: "fr",
    name: "French",
    localName: "Français",
    countries: ["FR", "BE", "CH", "CA", "LU"],
    speakers: 78000000,
    direction: "LTR",
    script: "Latin",
    difficulty: 6,
    vocabulary: 200000,
  },
  it: {
    ISO: "it",
    name: "Italian",
    localName: "Italiano",
    countries: ["IT", "CH"],
    speakers: 65000000,
    direction: "LTR",
    script: "Latin",
    difficulty: 5,
    vocabulary: 250000,
  },
  pt: {
    ISO: "pt",
    name: "Portuguese",
    localName: "Português",
    countries: ["PT", "BR", "AO", "MZ"],
    speakers: 220000000,
    direction: "LTR",
    script: "Latin",
    difficulty: 5,
    vocabulary: 250000,
  },
  ru: {
    ISO: "ru",
    name: "Russian",
    localName: "Русский",
    countries: ["RU", "BY", "KZ"],
    speakers: 258000000,
    direction: "LTR",
    script: "Cyrillic",
    difficulty: 4,
    vocabulary: 200000,
  },
  zh: {
    ISO: "zh",
    name: "Chinese",
    localName: "中文",
    countries: ["CN", "SG", "TW"],
    speakers: 1117000000,
    direction: "LTR",
    script: "Chinese characters",
    difficulty: 2,
    vocabulary: 50000, // Note: Chinese characters
  },
  ja: {
    ISO: "ja",
    name: "Japanese",
    localName: "日本語",
    countries: ["JP"],
    speakers: 128000000,
    direction: "LTR",
    script: "Kanji, Hiragana, Katakana",
    difficulty: 3,
    vocabulary: 500000, // Includes kanji
  },
  id: {
    ISO: "id",
    name: "Indonesian",
    localName: "Bahasa Indonesia",
    countries: ["ID"],
    speakers: 43000000,
    direction: "LTR",
    script: "Latin",
    difficulty: 7,
    vocabulary: 120000,
  },
  ar: {
    ISO: "ar",
    name: "Arabic",
    localName: "العربية",
    countries: ["SA", "IQ", "EG", "SY", "MA", "TN", "DZ", "LY"],
    speakers: 310000000,
    direction: "RTL",
    script: "Arabic",
    difficulty: 3,
    vocabulary: 120000,
  },
  ko: {
    ISO: "ko",
    name: "Korean",
    localName: "한국어",
    countries: ["KR"],
    speakers: 77000000,
    direction: "LTR",
    script: "Hangul",
    difficulty: 4,
    vocabulary: 210000,
  },
  se: {
    ISO: "se",
    name: "Swedish",
    localName: "Svenska",
    countries: ["SE", "FI"],
    speakers: 10000000,
    direction: "LTR",
    script: "Latin",
    difficulty: 5,
    vocabulary: 125000,
  },
  da: {
    ISO: "da",
    name: "Danish",
    localName: "Dansk",
    countries: ["DK"],
    speakers: 6000000,
    direction: "LTR",
    script: "Latin",
    difficulty: 5,
    vocabulary: 200000,
  },
  tr: {
    ISO: "tr",
    name: "Turkish",
    localName: "Türkçe",
    countries: ["TR"],
    speakers: 75000000, // This is an approximate number of native speakers.
    direction: "LTR",
    script: "Latin",
    difficulty: 4, // Difficulty can vary depending on the reference, this is just an example.
    vocabulary: 150000, // Approximate number of words in Turkish; actual number may vary.
  },
  fi: {
    ISO: "fi",
    name: "Finnish",
    localName: "Suomi",
    countries: ["FI"],
    speakers: 5500000,
    direction: "LTR",
    script: "Latin",
    difficulty: 3,
    vocabulary: 150000,
  },
  no: {
    ISO: "no",
    name: "Norwegian",
    localName: "Norsk",
    countries: ["NO"],
    speakers: 5300000,
    direction: "LTR",
    script: "Latin",
    difficulty: 5,
    vocabulary: 200000,
  },
  pl: {
    ISO: "pl",
    name: "Polish",
    localName: "Polski",
    countries: ["PL"],
    speakers: 45000000,
    direction: "LTR",
    script: "Latin",
    difficulty: 4,
    vocabulary: 170000,
  },
  th: {
    ISO: "th",
    name: "Thai",
    localName: "ไทย",
    countries: ["TH"],
    speakers: 20600000,
    direction: "LTR",
    script: "Thai",
    difficulty: 2,
    vocabulary: 60000,
  },
  cs: {
    ISO: "cs",
    name: "Czech",
    localName: "Čeština",
    countries: ["CZ"],
    speakers: 12000000,
    direction: "LTR",
    script: "Latin",
    difficulty: 4,
    vocabulary: 200000,
  },
  el: {
    ISO: "el",
    name: "Greek",
    localName: "Ελληνικά",
    countries: ["GR"],
    speakers: 13000000,
    direction: "LTR",
    script: "Greek",
    difficulty: 4,
    vocabulary: 150000,
  },
  he: {
    ISO: "he",
    name: "Hebrew",
    localName: "עברית",
    countries: ["IL"],
    speakers: 9000000,
    direction: "RTL",
    script: "Hebrew",
    difficulty: 4,
    vocabulary: 100000,
  },
  hi: {
    ISO: "hi",
    name: "Hindi",
    localName: "हिन्दी",
    countries: ["IN"],
    speakers: 341000000,
    direction: "LTR",
    script: "Devanagari",
    difficulty: 7,
    vocabulary: 120000,
  }
};